package hibernate;
// Generated Aug 8, 2011 3:48:28 PM by Hibernate Tools 3.2.1.GA



/**
 * Managerlogin generated by hbm2java
 */
public class Managerlogin  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String password;

    public Managerlogin() {
    }

    public Managerlogin(String login, String password) {
       this.login = login;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


